BEGIN;

CREATE SCHEMA IF NOT EXISTS careerops;

CREATE TABLE IF NOT EXISTS careerops.source_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL,
    profile_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT source_profiles_source_profile_key_uk UNIQUE (source, profile_key)
);

CREATE TABLE IF NOT EXISTS careerops.resumes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_profile_id bigint NOT NULL
        REFERENCES careerops.source_profiles (id),
    source_resume_id text NOT NULL,
    title text,
    raw_uri text,
    content_hash text,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT resumes_source_profile_resume_uk
        UNIQUE (source_profile_id, source_resume_id),
    CONSTRAINT resumes_seen_order_ck CHECK (last_seen_at >= first_seen_at),
    CONSTRAINT resumes_content_hash_ck CHECK (
        content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$'
    )
);

CREATE TABLE IF NOT EXISTS careerops.vacancies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL,
    source_entity_id text NOT NULL,
    source_employer_id text,
    title text,
    company_name text,
    description text,
    salary_from numeric,
    salary_to numeric,
    salary_currency text,
    location text,
    remote boolean,
    employment_type text,
    experience text,
    source_url text,
    relations text[],
    archived boolean,
    closed_for_applicants boolean,
    has_test boolean,
    response_letter_required boolean,
    response_url text,
    published_at timestamptz,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    latest_raw_uri text NOT NULL,
    latest_content_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vacancies_source_entity_uk UNIQUE (source, source_entity_id),
    CONSTRAINT vacancies_seen_order_ck CHECK (last_seen_at >= first_seen_at),
    CONSTRAINT vacancies_latest_content_hash_ck CHECK (
        latest_content_hash ~ '^[0-9a-f]{64}$'
    )
);

CREATE TABLE IF NOT EXISTS careerops.batch_runs (
    id uuid PRIMARY KEY,
    resume_id bigint NOT NULL REFERENCES careerops.resumes (id),
    search_query text,
    area_id text,
    period_days integer,
    pages integer,
    per_page integer,
    max_responses integer,
    professional_roles text[] NOT NULL DEFAULT '{}',
    cover_letter_mode text,
    live boolean NOT NULL,
    status text NOT NULL,
    discovered integer,
    prefiltered integer,
    full_fetched integer,
    accepted integer,
    submitted integer,
    confirmed integer,
    failed integer,
    stopped_on_captcha boolean,
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    s3_prefix text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT batch_runs_status_ck CHECK (
        status IN ('running', 'incomplete', 'finished')
    ),
    CONSTRAINT batch_runs_time_order_ck CHECK (
        finished_at IS NULL OR finished_at >= started_at
    ),
    CONSTRAINT batch_runs_finished_at_ck CHECK (
        status <> 'finished' OR finished_at IS NOT NULL
    ),
    CONSTRAINT batch_runs_counters_ck CHECK (
        (discovered IS NULL OR discovered >= 0)
        AND (prefiltered IS NULL OR prefiltered >= 0)
        AND (full_fetched IS NULL OR full_fetched >= 0)
        AND (accepted IS NULL OR accepted >= 0)
        AND (submitted IS NULL OR submitted >= 0)
        AND (confirmed IS NULL OR confirmed >= 0)
        AND (failed IS NULL OR failed >= 0)
    )
);

CREATE TABLE IF NOT EXISTS careerops.vacancy_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES careerops.batch_runs (id),
    vacancy_id bigint NOT NULL REFERENCES careerops.vacancies (id),
    stage text NOT NULL,
    accepted boolean NOT NULL,
    reason text NOT NULL,
    matched_domains text[] NOT NULL DEFAULT '{}',
    blocked_terms text[] NOT NULL DEFAULT '{}',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL,
    CONSTRAINT vacancy_decisions_run_vacancy_stage_uk
        UNIQUE (run_id, vacancy_id, stage)
);

CREATE TABLE IF NOT EXISTS careerops.applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_run_id uuid NOT NULL,
    batch_run_id uuid REFERENCES careerops.batch_runs (id),
    vacancy_id bigint NOT NULL REFERENCES careerops.vacancies (id),
    resume_id bigint NOT NULL REFERENCES careerops.resumes (id),
    submission_mode text NOT NULL,
    status text NOT NULL,
    confirmed boolean,
    requested_at timestamptz NOT NULL,
    finished_at timestamptz,
    cover_letter_uri text,
    request_uri text,
    result_uri text,
    before_uri text,
    after_uri text,
    error_type text,
    error_message text,
    upstream_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT applications_application_run_uk UNIQUE (application_run_id),
    CONSTRAINT applications_vacancy_resume_uk UNIQUE (vacancy_id, resume_id),
    CONSTRAINT applications_time_order_ck CHECK (
        finished_at IS NULL OR finished_at >= requested_at
    )
);

COMMIT;
