"""Публичные контракты границы CareerOPS Processing v2"""

from .artifacts import (
    FILTER_TRACE_SCHEMA_VERSION,
    P204_RESULT_SCHEMA_VERSION,
    P205_RESULT_SCHEMA_VERSION,
    FilterTraceArtifact,
    P204ResultArtifact,
    P205ResultArtifact,
    ProcessingArtifactKind,
    ProcessingArtifactRef,
)
from .common import (
    DataQualityStatus,
    EntityType,
    NormalizedRef,
    RawObservationRef,
    SourceLabel,
    SourceTextRef,
    SourceValue,
    TextBlock,
    ValueState,
)
from .compatibility import validate_bundle_for_ref
from .evidence import (
    RESUME_EVIDENCE_SET_SCHEMA_VERSION,
    EvidenceActorScope,
    EvidenceContext,
    EvidenceKind,
    EvidenceStrength,
    ResumeEvidence,
    ResumeEvidenceSet,
)
from .filtering import (
    FilterDecision,
    FilterEvidence,
    FilterOutcome,
    FilterPolicy,
    ProvenExclusion,
    RoleFamily,
    SeniorityLevel,
    WorkFormat,
)
from .manifest import MANIFEST_SCHEMA_VERSION, ProcessingInputManifest
from .normalized import (
    DataQualityReport,
    EducationEntry,
    Employer,
    ExperienceEntry,
    ExperienceRange,
    LanguageEntry,
    Location,
    NormalizedResume,
    NormalizedVacancy,
    ProjectEntry,
    Salary,
    WorkPreferences,
)
from .policy import BindingSnapshot, TargetPolicy
from .reasons import INITIAL_REASON_CODES, ReasonCode, ReasonNamespace
from .requirements import (
    REQUIREMENT_SET_SCHEMA_VERSION,
    Requirement,
    RequirementContext,
    RequirementGroup,
    RequirementGroupOperator,
    RequirementImportance,
    RequirementKind,
    RequirementModality,
    RequirementSet,
    RequirementThreshold,
    RequirementThresholdMetric,
)
from .reranking import (
    EVIDENCE_CANDIDATE_SET_SCHEMA_VERSION,
    EvidenceCandidate,
    EvidenceCandidateSet,
    RequirementEvidenceCandidates,
    RequirementSelectionState,
)
from .semantics import (
    SemanticPolarity,
    SemanticSourceRef,
    SemanticSubject,
    SemanticTimeSpan,
)
from .versions import JinaVersionBundle, ProcessingVersionBundle

__all__ = [
    "BindingSnapshot",
    "DataQualityReport",
    "DataQualityStatus",
    "EVIDENCE_CANDIDATE_SET_SCHEMA_VERSION",
    "EducationEntry",
    "Employer",
    "EntityType",
    "EvidenceActorScope",
    "EvidenceCandidate",
    "EvidenceCandidateSet",
    "EvidenceContext",
    "EvidenceKind",
    "EvidenceStrength",
    "ExperienceEntry",
    "ExperienceRange",
    "FILTER_TRACE_SCHEMA_VERSION",
    "FilterDecision",
    "FilterEvidence",
    "FilterOutcome",
    "FilterPolicy",
    "FilterTraceArtifact",
    "INITIAL_REASON_CODES",
    "JinaVersionBundle",
    "LanguageEntry",
    "Location",
    "MANIFEST_SCHEMA_VERSION",
    "NormalizedRef",
    "NormalizedResume",
    "NormalizedVacancy",
    "P204_RESULT_SCHEMA_VERSION",
    "P205_RESULT_SCHEMA_VERSION",
    "P204ResultArtifact",
    "P205ResultArtifact",
    "ProcessingArtifactKind",
    "ProcessingArtifactRef",
    "ProcessingInputManifest",
    "ProcessingVersionBundle",
    "ProjectEntry",
    "ProvenExclusion",
    "REQUIREMENT_SET_SCHEMA_VERSION",
    "RESUME_EVIDENCE_SET_SCHEMA_VERSION",
    "RawObservationRef",
    "ReasonCode",
    "ReasonNamespace",
    "Requirement",
    "RequirementContext",
    "RequirementEvidenceCandidates",
    "RequirementGroup",
    "RequirementGroupOperator",
    "RequirementImportance",
    "RequirementKind",
    "RequirementModality",
    "RequirementSelectionState",
    "RequirementSet",
    "RequirementThreshold",
    "RequirementThresholdMetric",
    "ResumeEvidence",
    "ResumeEvidenceSet",
    "RoleFamily",
    "Salary",
    "SemanticPolarity",
    "SemanticSourceRef",
    "SemanticSubject",
    "SemanticTimeSpan",
    "SeniorityLevel",
    "SourceLabel",
    "SourceTextRef",
    "SourceValue",
    "TargetPolicy",
    "TextBlock",
    "ValueState",
    "WorkFormat",
    "WorkPreferences",
    "validate_bundle_for_ref",
]
